/* 
 *******************************************************************************
 * WARNING - THIS FILE HAS BEEN GENERATED - DO NOT CHANGE
 * 
 * Filename:        drx_driver_version.h
 * Generated on:    Wed Oct 26 12:42:18 2005
 * Generated by:    Idefix 1.2.0
 * Generated from:  ../../../device/drx3973d/version
 * Parser start:    [entry point]
 * Output start:    [entry point]
 * 
 * filename         last modified               re-use  
 * -----------------------------------------------------
 * version.idf      Wed Oct 26 12:23:00 2005    -       
 * 
 * $(c) 2005 Micronas GmbH. All rights reserved.
 * 
 * This software and related documentation (the 'Software') are intellectual 
 * property owned by Micronas and are copyright of Micronas, unless 
 * specifically noted otherwise.
 * 
 * Any use of the Software is permitted only pursuant to the terms of the 
 * license agreement, if any, which accompanies, is included with or applicable 
 * to the Software ('License Agreement') or upon express written consent of 
 * Micronas. Any copying, reproduction or redistribution of the Software in 
 * whole or in part by any means not in accordance with the License Agreement 
 * or as agreed in writing by Micronas is expressly prohibited.
 * 
 * THE SOFTWARE IS WARRANTED, IF AT ALL, ONLY ACCORDING TO THE TERMS OF THE 
 * LICENSE AGREEMENT. EXCEPT AS WARRANTED IN THE LICENSE AGREEMENT THE SOFTWARE 
 * IS DELIVERED 'AS IS' AND MICRONAS HEREBY DISCLAIMS ALL WARRANTIES AND 
 * CONDITIONS WITH REGARD TO THE SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES AND 
 * CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIT 
 * ENJOYMENT, TITLE AND NON-INFRINGEMENT OF ANY THIRD PARTY INTELLECTUAL 
 * PROPERTY OR OTHER RIGHTS WHICH MAY RESULT FROM THE USE OR THE INABILITY TO 
 * USE THE SOFTWARE.
 * 
 * IN NO EVENT SHALL MICRONAS BE LIABLE FOR INDIRECT, INCIDENTAL, 
 * CONSEQUENTIAL, PUNITIVE, SPECIAL OR OTHER DAMAGES WHATSOEVER INCLUDING 
 * WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS 
 * INTERRUPTION, LOSS OF BUSINESS INFORMATION, AND THE LIKE, ARISING OUT OF OR 
 * RELATING TO THE USE OF OR THE INABILITY TO USE THE SOFTWARE, EVEN IF 
 * MICRONAS HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, EXCEPT 
 * PERSONAL INJURY OR DEATH RESULTING FROM MICRONAS' NEGLIGENCE. $
 * 
 *******************************************************************************
 */

#ifndef __DRX_DRIVER_VERSION__H__
#define __DRX_DRIVER_VERSION__H__ INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

#ifdef _IDEFIXTABLE_
#include <idefixtable.h>
extern IdefixTable_t drx_driver_version[];
#endif /* _IDEFIXTABLE_ */
                                                                            

/* 
 *==============================================================================
 * VERSION
 * version@/var/cvs/projects/drx3973d.cvsroot/hostcode/drxdriver/device/drx3973d
 *==============================================================================
 */

#define VERSION__A      0x0
#define   VERSION_MAJOR 0   
#define   VERSION_MINOR 9   
#define   VERSION_PATCH 171 

#ifdef __cplusplus
}
#endif

#endif /* __DRX_DRIVER_VERSION__H__ */

/* 
 * End of file (drx_driver_version.h)
 *******************************************************************************
 */
