#########################################################
#
# makefile
# Makefile to build the decoder on Unix-style systems.
#
#########################################################

###################################
# Variables controlling the build #
###################################

# Target to build
TARGET = decoder

# Root is up one level
PROJROOT = ..

# Object files to include
OBJECTS = \
	$(OBJDIR)decfile.o \
	$(OBJDIR)decoder.o \
	$(OBJDIR)decopts.o \
	$(OBJDIR)rdopts.o \
	$(OBJDIR)vc13dhtab.o \
	$(OBJDIR)vc1cropmv.o \
	$(OBJDIR)vc1deblock.o \
	$(OBJDIR)vc1debug.o \
	$(OBJDIR)vc1dec.o \
	$(OBJDIR)vc1dec3dh.o \
	$(OBJDIR)vc1dec3dhtab.o \
	$(OBJDIR)vc1decbit.o \
	$(OBJDIR)vc1decbitpl.o \
	$(OBJDIR)vc1decbitpltab.o \
	$(OBJDIR)vc1decblk.o \
	$(OBJDIR)vc1decblktab.o \
	$(OBJDIR)vc1decent.o \
	$(OBJDIR)vc1decmb.o \
	$(OBJDIR)vc1decmbtab.o \
	$(OBJDIR)vc1decmv.o \
	$(OBJDIR)vc1decpic.o \
	$(OBJDIR)vc1decpictab.o \
	$(OBJDIR)vc1decseq.o \
	$(OBJDIR)vc1decslice.o \
	$(OBJDIR)vc1deczz.o \
	$(OBJDIR)vc1derivemv.o \
	$(OBJDIR)vc1gentab.o \
	$(OBJDIR)vc1hrd.o \
	$(OBJDIR)vc1interp.o \
	$(OBJDIR)vc1iquant.o \
	$(OBJDIR)vc1itrans.o \
	$(OBJDIR)vc1pred.o \
	$(OBJDIR)vc1predcbp.o \
	$(OBJDIR)vc1preddcac.o \
	$(OBJDIR)vc1predmv.o \
	$(OBJDIR)vc1recon.o \
	$(OBJDIR)vc1scalemv.o \
	$(OBJDIR)vc1smooth.o \
	$(OBJDIR)vc1tools.o \
	$(OBJDIR)vc1zztab.o \

# Include the generic rules
include $(PROJROOT)/makedefs

