//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TSReader.rc
//
#define IDC_RECORD_PID_LOAD             3
#define IDC_STREAM_MONITOR_SAVE         3
#define IDC_RECORD_PID_SAVE             4
#define IDC_STREAM_MONITOR_SETTINGS     4
#define IDC_RECORD_TABLES_LOAD          5
#define IDC_RECORD_TABLE_SAVE           6
#define IDD_SI_PARSER                   100
#define IDC_STATUS                      101
#define IDC_SI_TREE                     102
#define IDC_SI_TEXT                     103
#define IDC_SI_PACKETS_PAT              104
#define IDC_SI_PACKETS_PMT              105
#define IDC_SI_PACKETS_NIT              106
#define IDC_SI_PACKETS_SDT              107
#define IDC_SI_PACKETS_EIT              108
#define IDC_SI_PACKETS_CAT              109
#define IDC_SI_CRCS_PAT                 110
#define IDC_SI_CRCS_PMT                 111
#define IDC_SI_CRCS_NIT                 112
#define IDC_SI_CRCS_SDT                 113
#define IDC_SI_CRCS_EIT                 114
#define IDC_SI_CRCS_CAT                 115
#define IDC_SI_FRAMING_PAT              116
#define IDC_SI_RATE                     116
#define IDC_SI_FRAMING_PMT              117
#define IDC_SI_RECORDED                 117
#define IDC_SI_FRAMING_NIT              118
#define IDC_SI_CONTINUITY               118
#define IDC_SI_FRAMING_SDT              119
#define IDC_SI_BITRATE                  119
#define IDC_SI_FRAMING_EIT              120
#define IDC_SI_FRAMING_CAT              121
#define IDC_EXPORT_SI_PAT               122
#define IDC_EXPORT_SI_PMTS              123
#define IDC_EXPORT_SI_CAT               124
#define IDC_EXPORT_SI_NIT               125
#define IDC_EXPORT_SI_SDT               126
#define IDC_EXPORT_SI_EIT               127
#define IDD_EXPORT_SI_HOOK              128
#define IDC_SI_PARSER_EXPORT            129
#define IDC_SI_PARSER_IP_DVB_MODE       130
#define IDC_SI_PARSER_PLUGINS           131
#define IDC_SI_PARSER_ABOUT             132
#define IDD_DVB_LOGO                    1000
#define IDC_PIDS_SCROLL                 1000
#define IDI_SI_CAT                      1001
#define IDC_PIDS_BORDER                 1001
#define IDI_SI_DESCRIPTOR               1002
#define IDC_SI_PARSER_RECORD            1002
#define IDI_SI_EIT                      1003
#define IDC_RECORD_FILE                 1003
#define IDC_SI_PARSER_RECORD_ALL        1003
#define IDI_SI_NIT                      1004
#define IDC_RECORD_BROWSE               1004
#define IDC_SI_PARSER_RECORD_ALL2       1004
#define IDI_SI_PAT                      1005
#define IDC_RECORD_VIDEO_ES             1005
#define IDI_SI_PCR                      1006
#define IDC_RECORD_AUDIO_ES             1006
#define IDI_SI_PMT                      1007
#define IDC_RECORD_OTHER_ES             1007
#define IDI_SI_SDT                      1008
#define IDC_RECORD_VIDEO_ES_CAPTION     1008
#define IDI_SI_USER_ES                  1009
#define IDC_RECORD_AUDIO_ES_CAPTION     1009
#define IDI_SI_AUDIO_ES                 1010
#define IDC_MANUAL_CAPTION              1010
#define IDC_RECORD_OTHER_ES_CAPTION     1010
#define IDD_RECORD                      1011
#define IDC_RECORD_NO_NULLS             1011
#define IDC_RECORD_AUDIO_ES_CAPTION2    1012
#define IDD_IPDVB_PID                   1012
#define IDC_RECORD_MPEG_AUDIO           1013
#define IDI_SI_BASE                     1013
#define IDC_RECORD_AC3_AUDIO            1014
#define IDC_SI_PARSER_EXPORT_NIT        1014
#define IDI_SI_BASE2                    1014
#define IDC_EXPORT_SI_SDT_THIS_MUX      1015
#define IDI_SI_IP                       1015
#define IDC_SI_PARSER_EXPORT_EIT        1015
#define IDC_RECORD_DTS_AUDIO            1015
#define IDC_BUTTON1                     1016
#define IDI_SI_VCT                      1016
#define IDC_ARCHIVE_CHANNELS_DEFAULT_NAME 1016
#define IDC_ARCHIVE_RUN_FORCE_NEW       1016
#define IDC_MANUAL_ES_MPEG_VIDEO        1016
#define IDC_VIEW_ARCHIVE_BROWSE         1016
#define IDC_RECORD_ALL_AUDIO            1016
#define IDC_SAVE_ALL_EPG_BROWSE         1016
#define IDC_UNSCRAMBLED_PID_COLOR_BROWSE 1016
#define IDC_EXPORT_SI_GENERAL_INFO      1016
#define IDC_EPG_EVENT_BACK_COLOR        1016
#define IDC_DEBUG                       1016
#define IDC_VLC_SETTINGS_DEFAULT        1016
#define IDC_EPG_MANUAL_ADD_15           1016
#define IDC_RECORD_TABLES_ADD           1016
#define IDC_EXPORT_NIT_BROWSE           1016
#define IDC_EIT_SERVER_REFRESH_CONNECTIONS 1016
#define IDC_GPS_OUTPUT_FILE_BROWSE      1016
#define IDC_IPDVB_PID_LIST              1017
#define IDI_SI_TDT                      1017
#define IDC_ARCHIVE_RUN_RESET_MIN_MAX   1017
#define IDC_MANUAL_ES_MPEG_AUDIO        1017
#define IDC_RECORD_ALL_OTHER            1017
#define IDC_UNSCRAMBLED_INACTIVE_PID_COLOR_BROWSE 1017
#define IDC_EPG_CHANNEL_BACK_COLOR      1017
#define IDC_EPG_MANUAL_ADD_30           1017
#define IDI_SI_SIT                      1018
#define IDC_DISEQC_COMMAND              1018
#define IDC_SI_PARSER_RECORD_PID        1018
#define IDC_MANUAL_ES_AC3_AUDIO         1018
#define IDC_SCRAMBLED_PID_COLOR_BROWSE  1018
#define IDC_EPG_SELECTED_BACK_COLOR     1018
#define IDC_EPG_MANUAL_ADD_60           1018
#define IDI_SI_CDT                      1019
#define IDC_SORT_RATE                   1019
#define IDC_SCRAMBLED_INACTIVE_PID_COLOR_BROWSE 1019
#define IDC_EPG_PRIMARY_TEXT_COLOR      1019
#define IDI_SI_MMT                      1020
#define IDC_SORT_PID                    1020
#define IDC_HIGHLIGHT_PID_COLOR_BROWSE  1020
#define IDC_EPG_SECONDARY_TEXT_COLOR    1020
#define IDC_SORT_DECENDING              1021
#define IDI_SI_VIDEO_ES                 1021
#define IDC_EPG_TIME_GRID_COLOR         1021
#define IDC_RECORD_SPLIT_4GB            1022
#define IDD_ABOUT                       1022
#define IDC_RECORD_SPLIT                1022
#define IDC_RECORD_SPLIT_CAPTION        1023
#define IDD_EVALUATION                  1023
#define IDC_EXPORT_SI_PID_CHART         1024
#define IDD_RECORD_PID_SELECT           1024
#define IDC_SI_TEXT_EXPORT              1025
#define IDD_TUNE_TWINHAN                1025
#define IDC_EXPORT_SI_MPEG_STATS        1025
#define IDC_VERSION                     1026
#define IDD_STRADIS                     1026
#define IDR_MAIN                        1026
#define IDC_EVALUATE                    1027
#define IDD_MEMORY                      1027
#define IDC_BUILT                       1027
#define IDC_DAYS_LEFT                   1028
#define IDD_RESOLUTION_WARNING          1028
#define IDC_LICENSE                     1029
#define IDI_INFO                        1029
#define IDC_SERIAL_NUMBER               1030
#define IDD_LICENSE                     1030
#define IDC_UNLOCK_CODE                 1031
#define IDD_THUMBNAIL_REFRESH_RATE      1031
#define IDC_PURCHASE                    1032
#define IDD_THUMBNAIL_WARNING           1032
#define IDC_SUPPORT                     1033
#define IDC_RECORD_PID_FOLDER           1034
#define IDD_SOURCE                      1034
#define IDC_EXPORT_SI_ALL               1035
#define IDD_MANUAL_CHANNELS             1035
#define IDC_RECORD_PID_NO_HEADER        1036
#define IDD_MANUAL_CHANNEL_EDIT         1036
#define IDC_RECORD_PID_ONE_FILE         1037
#define IDD_PROGRAM_STREAM_WARNING      1037
#define IDD_XNS_SERVER                  1038
#define IDB_ACTIVITY                    1040
#define IDD_VLC_SETTINGS                1041
#define IDD_VLC_WARNING                 1042
#define IDD_SI_PARSER_SMALL             1043
#define IDC_VIDEO_FRAME                 1044
#define IDD_BUFFER_SIZES                1044
#define IDC_RECORD_SPLIT_SIZE           1045
#define IDD_PID_WARNING                 1045
#define IDC_DISEQC3                     1046
#define IDC_RECORD_TITLE                1046
#define IDC_TO_STRADIS                  1047
#define IDC_SI_PARSER_TO_STRADIS        1047
#define IDD_VLC_CONNECTION_DIALOG       1047
#define IDC_RECORD_LIMIT_SIZE           1047
#define IDC_OUTPUT_FOLDER_CAPTION       1048
#define IDD_FILE_NAME_FORMAT            1048
#define IDC_RECORD_PID_BROWSE           1049
#define IDI_RUN_1                       1049
#define IDC_CONTINUITY_INDICATOR        1050
#define IDI_RUN_2                       1050
#define IDC_MEMORY_TAGS                 1051
#define IDI_RUN_3                       1051
#define IDC_MEMORY_CHART                1052
#define IDI_RUN_4                       1052
#define IDC_NOT_ENABLED                 1053
#define IDI_RUN_5                       1053
#define IDI_RECORD                      1054
#define IDI_BLANK                       1055
#define IDI_STREAM                      1056
#define IDC_TUNER_MUX_LIST              1057
#define IDD_ROKU1000_SETTINGS           1057
#define IDI_SI_USER_VBI                 1057
#define IDC_TUNER_SATELLITE_LIST        1058
#define IDD_ROKU_TRACE                  1058
#define IDI_SI_DATA                     1058
#define IDC_TUNER_MUX_TITLE             1059
#define IDD_SERIAL_CONTROL              1059
#define IDI_SI_MGT                      1059
#define IDC_SEPERATOR                   1060
#define IDD_CONTROL_SERVER              1060
#define IDC_RESOLUTION_DONT_SHOW        1061
#define IDD_PID_LIST                    1061
#define IDC_RECORD_TS                   1062
#define IDB_TXT_TXT                     1062
#define IDC_RECORD_PS                   1063
#define IDB_TXT_SUB                     1063
#define IDD_CONFIRM_ATSC_RC             1063
#define IDB_TXT_CC                      1064
#define IDR_IP_POPUP                    1064
#define IDC_BOGUS                       1065
#define IDB_TXT_VPS                     1065
#define IDD_IP_SETTINGS                 1065
#define IDC_LICENSE_TEXT                1066
#define IDB_TXT_ITXT                    1066
#define IDD_IP_DEVICE                   1066
#define IDC_REFRESH_RATE                1067
#define IDB_TXT_USER                    1067
#define IDI_SI_USER_SUBTL               1067
#define IDC_THUMBNAIL_WARNING_DONT_ASK  1068
#define IDB_TXT_422                     1068
#define IDR_NIT_POPUP                   1068
#define IDC_SOURCE_LIST                 1069
#define IDR_IP_POPUP_PID                1069
#define IDC_COMMAND_LINE_PARAMETERS     1070
#define IDI_SI_IP_STREAMING             1070
#define IDR_IP_POPUP_MAC                1070
#define IDC_BUFFER_FILL                 1071
#define IDC_MANUAL_CHANNEL_LIST         1072
#define IDC_PIPE_FILL                   1072
#define IDI_SI_IP_SAVING                1072
#define IDC_ADD_MANUAL_CHANNEL          1073
#define IDB_TXT_WSS                     1073
#define IDD_PID_PIE_CHART               1073
#define IDC_DELETE_MANUAL_CHANNEL       1074
#define IDB_ATSC_CC                     1074
#define IDI_DVBSMALL_LOGO               1074
#define IDC_ADD_MANUAL_CHANNEL2         1075
#define IDC_MANUAL_CHANNEL_NUMBER       1075
#define IDC_EDIT_MANUAL_CHANNEL         1075
#define IDC_MANUAL_PROGRAM_NUMBER       1075
#define IDB_ASPECT_43                   1075
#define IDD_LITE_CHART_WARNING          1075
#define IDI_SI_BAT                      1075
#define IDC_LIST1                       1076
#define IDC_MANUAL_ES_LIST              1076
#define IDC_TRACE_LIST                  1076
#define IDD_SERIAL_CONTROL_RX_TYPES     1076
#define IDC_PID_LISTBOX                 1076
#define IDB_ASPECT_149                  1076
#define IDC_IP_DEVICE_LIST              1076
#define IDC_TABLE_VIEWER_LIST           1076
#define IDC_ARCHIVE_VIEW_LIST           1076
#define IDC_CAM_LIST                    1076
#define IDC_PROFILE_NEW_LIST            1076
#define IDC_INTERFACE_ADDRESS           1076
#define IDC_MDI_DEBUG                   1076
#define IDC_DESCRIPTOR_LIST             1076
#define IDC_MONITOR_LIST                1076
#define IDC_EPG_SCHEDULE_LIST           1076
#define IDC_RECORD_TABLES_PID_TABLE_LIST 1076
#define IDC_EIT_SERVER_CONNECTIONS      1076
#define IDC_MANUAL_CHANNEL_ES_TYPE      1077
#define IDB_ASPECT_169                  1077
#define IDD_EPG_GRID_SETTINGS           1077
#define IDC_MANUAL_CHANNEL_ES_PID       1078
#define IDB_ATSC_RC                     1078
#define IDC_MANUAL_ES_ADD               1079
#define IDR_ACCELERATOR_TOP             1079
#define IDC_MANUAL_ES_DELETE            1080
#define IDR_TEST                        1080
#define IDC_MANUAL_PCR_PID              1081
#define IDC_SCROLL_THUMBNAILS           1081
#define IDI_TV_Y                        1081
#define IDC_CURRENT_SOURCE              1082
#define IDI_TV_Y7                       1082
#define IDC_RECORD_STREAM_CAPTION       1083
#define IDC_SOURCE_PARAMETERS           1083
#define IDI_TV_Y7FV                     1083
#define IDC_RECORD_TITLE_CAPTION        1084
#define IDC_SOURCE_MAX_PIDS             1084
#define IDI_TV_G                        1084
#define IDC_SI_PACKETS_SDT_CAPTION      1085
#define IDC_SOURCE_STOPABLE             1085
#define IDI_TV_PG                       1085
#define IDC_SI_PACKETS_EIT_CAPTION      1086
#define IDC_SOURCE_CAPABILITIES         1086
#define IDI_TV_14                       1086
#define IDC_SOURCE_CAPTION              1087
#define IDI_TV_MA                       1087
#define IDC_NO_PS_WARNING               1088
#define IDI_CC                          1088
#define IDC_PID_CHART_DISABLE           1089
#define IDI_SI_SDT_OTHER                1089
#define IDD_TABLE_VIEWER                1089
#define IDI_SI_NIT_OTHER                1090
#define IDD_GRAPH_REFRESH               1090
#define IDC_TOGGLE_CRYPT                1091
#define IDD_AUTO_RESTART                1091
#define IDC_XNS_SERVER_PORT             1092
#define IDB_AUD_MPEG                    1092
#define IDC_ACTIVITY1                   1093
#define IDB_AUD_AC3                     1093
#define IDD_ARCHIVE_SETUP               1093
#define IDC_ACTIVITY2                   1094
#define IDC_VLC_EXE_LOCATION            1094
#define IDD_ARCHIVE_RUN                 1094
#define IDB_ASPECT_AFD                  1094
#define IDC_ACTIVITY3                   1095
#define IDC_VLC_CONTROL_ENABLE          1095
#define IDI_LOG_INFO                    1095
#define IDC_ACTIVITY4                   1096
#define IDC_VLC_PORT                    1096
#define IDI_LOG_STOP                    1096
#define IDC_ACTIVITY5                   1097
#define IDC_VLC_BROWSE                  1097
#define IDI_LOG_WARNING                 1097
#define IDC_ACTIVITY6                   1098
#define IDC_VLC_NO_WARNING              1098
#define IDC_VLC_CONTROL_SEND_LENGTH     1098
#define IDD_ARCHIVE_VIEW                1098
#define IDC_ACTIVITY7                   1099
#define IDC_ATSC_MODE                   1099
#define IDI_DELETE                      1099
#define IDC_ACTIVITY8                   1100
#define IDI_PLAY                        1100
#define IDC_INCLUDE_CA                  1100
#define IDC_LITE_WARNING                1101
#define IDD_EIT_SERVER                  1101
#define IDI_SI_BAT_SELECTED             1101
#define IDD_SAVE_EPG                    1102
#define IDI_DVB_LOGO_SMALL_RED          1102
#define IDC_VLC_CONFIG_NUMBER           1103
#define IDD_PID_CHART_COLORS            1103
#define IDI_DVB_LOGO_SMALL_BLACK        1103
#define IDC_VLC_CONFIG_DESCRIPTION      1104
#define IDC_VLC_CONFIG_COMMAND          1105
#define IDC_VLC_CONFIG_UP               1106
#define IDD_CAM_MENU                    1106
#define IDC_VLC_CONFIG_DOWN             1107
#define IDC_STREAMING_PIPE_SIZE         1107
#define IDC_THUMBNAIL_PIPE_SIZE         1108
#define IDC_NO_MORE_PID_WARNING         1108
#define IDR_PROFILES                    1108
#define IDC_DONT_SHOW                   1109
#define IDC_RECORD_PID_APPEND           1110
#define IDB_PROFILE_TOOLBAR             1110
#define IDC_RECORD_MB_LIMIT             1111
#define IDD_MOSAIC                      1111
#define IDB_VID_MPEG2                   1111
#define IDC_RECORD_SEC_LIMIT            1112
#define IDR_BAT_POPUP                   1112
#define IDB_VID_MPEG4                   1112
#define IDC_CHANGE_FILENAME_FORMAT      1113
#define IDR_TDT_POPUP                   1113
#define IDB_VID_H264                    1113
#define IDD_PROFILE_NEW                 1114
#define IDC_RECORD_FILENAME_SAMPLE      1115
#define IDR_PROFILES_POPUP              1115
#define IDC_FORMAT_STRING               1116
#define IDD_SETTINGS                    1116
#define IDR_SDT_POPUP                   1116
#define IDC_FORMAT_SAMPLE               1117
#define IDC_ROKU_IP                     1117
#define IDD_SETTINGS_THREADS            1117
#define IDR_SDT_CH_POPUP                1117
#define IDC_ROKU_USERNAME               1118
#define IDD_SETTINGS_EIT                1118
#define IDC_ROKU_PASSWORD               1119
#define IDD_SETTINGS_THUMBNAILS         1119
#define IDC_ROKU_MPEGPSPLAY_LOCATION    1120
#define IDD_SETTINGS_IPDVB              1120
#define IDC_ROKU_TRACE_DISABLED         1121
#define IDD_SETTINGS_PARSER             1121
#define IDC_SERIAL_CONTROL_PORT         1122
#define IDD_SETTINGS_CHART              1122
#define IDC_SERIAL_CONTROL_ENABLED      1123
#define IDD_SETTINGS_UI                 1123
#define IDC_CONTROL_SERVER_ENABLED      1124
#define IDD_SETTINGS_RECEIVER           1124
#define IDC_CONTROL_SERVER_PORT         1125
#define IDD_SETTINGS_CONTROL_SERVER     1125
#define IDC_SOURCE_BOX                  1126
#define IDD_SETTINGS_SPLIT_FILENAMES    1126
#define IDC_NETWORK_TYPE_FRAME          1127
#define IDD_SETTINGS_DVHS               1127
#define IDC_NIT_TAG                     1128
#define IDD_SETTINGS_SOURCE             1128
#define IDC_ROKU_PLAYBACK_MPEGPSPLAY    1129
#define IDD_PLUGIN_SETTINGS             1129
#define IDC_ROKU_PLAYBACK_CINEMA6       1130
#define IDD_FORWARDER_SETUP             1130
#define IDC_ROKU_PLAYBACK_CAPTION       1131
#define IDD_FORWARDER_RUN               1131
#define IDC_ROKU_TRACE_COPY             1132
#define IDD_EPG_GOTO_CHANNEL            1132
#define IDD_EPG_FIND_STRING             1133
#define IDC_RECORD_PMT_DEFACTO          1134
#define IDD_SETTINGS_ROKU               1134
#define IDC_RECORD_PMT_ETSI             1135
#define IDC_PID_LIST_COPY               1135
#define IDD_SETTINGS_STRADIS            1135
#define IDC_ATSC_RC_FCC                 1136
#define IDD_SETTINGS_VLC                1136
#define IDC_ATSC_RC_OUTSIDE_FCC         1137
#define IDD_SETTINGS_CA                 1137
#define IDC_ATSC_RC_CONFIRM             1138
#define IDD_SETTINGS_XNS                1138
#define IDC_EXPORT_SI_THUMBNAILS        1139
#define IDD_MDI_INDEX                   1139
#define IDC_IP_SAVE_FOLDER              1140
#define IDD_DESCRIPTOR_USAGE            1140
#define IDC_IP_SAVE_FOLDER_ELIPSES      1141
#define IDD_STREAM_MONITOR              1141
#define IDC_RECORD_LIMIT                1142
#define IDI_MONITOR_GREEN               1142
#define IDI_MONITOR_RED                 1143
#define IDD_EPG_DATE                    1143
#define IDC_LITE_CHART_NO_WARN          1144
#define IDI_MONITOR_HALF                1144
#define IDD_CHART_SAVE_DATA             1144
#define IDI_MONITOR_YELLOW              1144
#define IDC_EPG_WIDTH                   1145
#define IDI_MONITOR_GREY                1145
#define IDD_STRADIS_SETTINGS            1145
#define IDC_EPG_HEIGHT                  1146
#define IDD_EPG_SHOW_SCHEDULE           1146
#define IDI_SI_NIT_IGNORED              1146
#define IDC_EPG_ONLY_EPG_CHANNELS       1147
#define IDI_BOMB                        1147
#define IDC_EPG_THIS_MUX_ONLY           1148
#define IDD_BOMB_WARNING                1148
#define IDI_MONITOR_DISABLED            1148
#define IDC_ROKU_AUTOSCROLL             1149
#define IDC_EPG_SHOW_TIME_GRID          1149
#define IDD_EPG_MANUAL                  1149
#define IDC_TABLE_VIEWER_PID            1150
#define IDC_EPG_GRID_ON_TOP             1150
#define IDD_RECORD_ADVANCED_FILE        1150
#define IDC_TABLE_VIEWER_PID_FORMAT     1151
#define IDD_RECORD_ADVANCED_MUX         1151
#define IDC_EPG_RECORD_PS               1151
#define IDC_GRAPH_REFRESH_RATE          1152
#define IDD_EMAIL_SETUP                 1152
#define IDC_EPG_UPDATE_REALTIME         1152
#define IDC_AUTORESTART_PAT_CHANGE      1153
#define IDC_GRAPH_HISTORICAL_POINTS     1153
#define IDC_AUTORESTART_STOP            1154
#define IDD_STREAM_MONITOR_SETTINGS     1154
#define IDC_AUTORESTART_STOP_DELAY      1155
#define IDR_STREAM_MONITOR_POPUP        1155
#define IDC_AUTORESTART_NO_TUNE_DIALOG  1156
#define IDD_SCHEDULER_WARNING           1156
#define IDR_NIT_EXPORT                  1156
#define IDD_EIT_LANGUAGE_SETTINGS       1157
#define IDC_ARCHIVE_CHANNEL_LIST        1158
#define IDC_ARCHIVE_CHANNEL_ENABLED     1159
#define IDD_RECORD_TABLES               1159
#define IDC_ARCHIVE_CHANNEL_OUTPUT_LOCATION 1160
#define IDD_THUMBNAIL_REFRESH_RATE_PRO  1160
#define IDC_ARCHIVE_CHANNEL_OUTPUT_NAME 1161
#define IDC_ARCHIVE_BLOCKSIZE           1162
#define IDC_ARCHIVE_CHANNEL_CURRENTEPG  1163
#define IDB_BITMAP1                     1163
#define IDC_ARCHIVE_CHANNEL_REMOTE_EPG  1164
#define IDB_BITMAP2                     1164
#define IDB_VID_VC1                     1165
#define IDD_EXPORT_NIT_INI              1165
#define IDC_ARCHIVE_CHANNEL_EPG_SERVER  1166
#define IDB_BVID_H264                   1166
#define IDD_ARCHIVE_WAIT_EPG            1166
#define IDC_ARCHIVE_CHANNEL_HALFHOUR    1167
#define IDB_BVID_MPEG2                  1167
#define IDR_EPG_POPUP                   1167
#define IDC_RESTART_NOBEEP              1168
#define IDB_BVID_MPEG4                  1168
#define IDD_EPG_SCHEDULE_SETTINGS       1168
#define IDC_ARCHIVE_CLONE               1169
#define IDB_BVID_VC1                    1169
#define IDD_EPG_MANUAL_NO_SOURCE_PARAMETERS 1169
#define IDC_STATISTICS_FRAME            1170
#define IDB_BAUD_AC3                    1170
#define IDR_PCR_POPUP                   1170
#define IDD_TABLE_VIEWER_PRO            1170
#define IDC_ARCHIVE_VIEW_BASE_FOLDER    1171
#define IDB_BAUD_MPEG                   1171
#define IDR_MANUAL_EPG_CURRENT          1171
#define IDC_ARCHIVE_VIEW_LOAD           1172
#define IDB_VID_DCII                    1172
#define IDD_CHECK_NEW_VERSION           1172
#define IDC_VIEW_ARCHIVE_PLAY           1173
#define IDB_BVID_DCII                   1173
#define IDC_VIEW_ARCHIVE_DELETE         1174
#define IDI_UPDATE_GOOD                 1174
#define IDB_AUD_AAC                     1174
#define IDC_VIEW_ARCHIVE_SHOW_LOCAL_TIME 1175
#define IDI_UPDATE                      1175
#define IDB_BAUD_AAC                    1175
#define IDC_VIEW_ARCHIVE_LOAD_PROGRESS  1176
#define IDI_UPDATE_BAD                  1176
#define IDC_VIEW_ARCHIVE_DESCRIPTION    1177
#define IDR_ES_POPUP                    1177
#define IDI_FWD_1                       1177
#define IDC_EIT_SERVER_ENABLED          1178
#define IDD_GPS_SIGNAL_EXPORT           1178
#define IDI_FWD_2                       1178
#define IDC_EIT_SERVER_PORT             1179
#define IDD_FORWARD_SETTINGS            1179
#define IDI_FWD_3                       1179
#define IDC_ARCHIVE_SILENT              1180
#define IDI_FWD_4                       1180
#define IDD_CC_MASK_STREAMS             1180
#define IDC_ARCHIVE_SETUP_MEMORY        1181
#define IDC_ARCHIVE_LOCAL_TIME          1181
#define IDD_CC_DUMP_STREAMS_HOOK        1181
#define IDI_SI_BIT                      1181
#define IDC_ARCHIVE_RUN_DEBUG           1182
#define IDD_AUTO_RECORD_NO_PROGRAM      1182
#define IDC_ARCHIVE_EMAIL               1183
#define IDD_AUDIO_THUMBNAIL_SETTINGS    1183
#define IDC_ARCHIVE_SMTP_SERVER         1184
#define IDB_BITMAP3                     1184
#define IDC_ARCHIVE_EMAIL_FROM          1185
#define IDC_SAVE_EPG_FOLDER             1186
#define IDC_ARCHIVE_SMTP_USERNAME       1186
#define IDC_ARCHIVE_SMTP_PASSWORD       1187
#define IDC_RECORD_PID_INCLUDE_PCR      1190
#define IDC_CAM_APPLICATION_TYPE        1191
#define IDC_CAM_APPLICATION_INFO        1192
#define IDC_CAM_HEADER                  1193
#define IDC_CAM_SUB_HEADER              1194
#define IDC_CAM_BOTTOM_LINE             1195
#define IDC_CAM_ERROR_INDICATOR         1196
#define IDC_ARCHIVE_VIEW_COPY_FILENAME  1197
#define IDC_ARCHIVE_AUTO_DELETE         1198
#define IDC_ARCHIVE_AUTO_DELETE_GB      1199
#define IDC_ARCHIVE_WARNING_GB          1200
#define IDC_ARCHIVE_ERROR_GB            1201
#define IDC_CURRENT_SOURCE_CAPTION      1201
#define IDC_SOURCE_PARAMETERS_CAPTION   1202
#define IDC_SOURCE_MAX_PIDS_CAPTION     1203
#define IDC_SOURCE_STOPABLE_CAPTION     1204
#define IDC_SOURCE_CAPABILITIES_CAPTION 1205
#define IDC_PROFILE_NEW_NAME            1206
#define IDC_SETTINGS_TREE               1207
#define IDC_TITLE                       1208
#define IDC_DATA_INPUT_CRITICAL         1209
#define IDC_DATA_INPUT_HIGH             1210
#define IDC_DATA_INPUT_NORMAL           1211
#define IDC_DATA_INPUT_LOW              1212
#define IDC_STREAM_PROCESSING_HIGH      1213
#define IDC_STREAM_PROCESSING_NORMAL    1214
#define IDC_STREAM_PROCESSING_LOW       1215
#define IDC_PROCESS_REALTIME            1216
#define IDC_PROCESS_HIGH                1217
#define IDC_PROCESS_ABOVE_NORMAL        1218
#define IDC_PROCESS_NORMAL              1219
#define IDC_PROCESS_BELOW_NORMAL        1220
#define IDC_PROCESS_LOW                 1221
#define IDC_THUMBNAIL_ANIMATED          1221
#define IDC_THUMBNAIL_PROCESSING_HIGH   1222
#define IDC_THUMBNAIL_FULL_THUMBNAILS   1222
#define IDC_THUMBNAIL_PROCESSING_NORMAL 1223
#define IDC_THUMBNAIL_AUDIO             1223
#define IDC_THUMBNAIL_PROCESSING_LOW    1224
#define IDC_THUMBNAIL_FULL_SIZE_SAVED   1224
#define IDC_THUMBNAIL_HIDE_ICONS        1225
#define IDC_THUMBNAIL_PROCESSING_DISABLED 1225
#define IDC_THUMBNAIL_LARGE             1226
#define IDC_THUMBNAIL_REFRESH_RATE      1227
#define IDC_THUMBNAIL_SAVE_ALL_SAME_NAME 1228
#define IDC_IP_AUTO_EXPAND              1228
#define IDC_THUMBNAIL_SHOW_SCRAMBLED    1229
#define IDC_THUMBNAIL_WAIT_CA           1230
#define IDC_EIT_KEEP_PAST_DATA          1230
#define IDC_PARSER_COUNT_CONTINUITY     1231
#define IDC_PARSER_IGNORE_CRC           1232
#define IDC_CHART_REALTIME              1232
#define IDC_PARSER_DCII_PMT_80          1233
#define IDC_CHART_REFRESH_RATE          1233
#define IDC_PARSER_IGNORE_DVB_EIT_SDT   1234
#define IDC_UI_AUTO_EXPAND_PMTS         1234
#define IDC_PARSER_IGNORE_PMT_65500     1235
#define IDC_UI_DECIMAL_PIDS             1235
#define IDC_DVHS_AUTO_REC_STOP          1235
#define IDC_PARSER_PLAIN_CA_DESCRIPTOR  1236
#define IDC_UI_HIDE_MINIMIZED           1236
#define IDC_DVHS_AUTO_POWER             1236
#define IDC_CHART_STYLE                 1236
#define IDC_PARSER_SDT_CURRENT_MUX      1237
#define IDC_UI_KEEP_SPECIAL_XML         1237
#define IDC_DVHS_ATSC_PIDS              1237
#define IDC_SOURCE_SELECTED_SOURCE      1237
#define IDC_PARSER_TIMESTAMP_PACKETS    1238
#define IDC_PLUGINS_PREFERED_CA_ID_ENABLED 1238
#define IDC_PLUGINS_PREFERED_CA_ID      1239
#define IDC_MAXIMUM_MPEG_PICTURES       1240
#define IDC_MAXIMUM_DCII_PICTURES       1241
#define IDC_FORWARDER_CHANNEL_LIST      1241
#define IDC_FORWARDER_CHANNEL_ENABLED   1242
#define IDC_MAXIMUM_THUMBNAIL_THREADS   1242
#define IDC_FORWARDER_CHANNEL_DESTINATION 1243
#define IDC_FORWARDER_CHANNEL_PORT      1244
#define IDC_FORWARDER_SAP_GROUP         1245
#define IDC_FORWARDER_SAP_ENABLED       1246
#define IDC_FORWARDER_MUX_ENABLED       1247
#define IDC_FORWARDER_MUX_DESTINATION   1248
#define IDC_FORWARDER_MUX_PORT          1249
#define IDC_FORWARDER_MULTICAST_TTL     1249
#define IDC_FORWARDER_MUX_NO_NULLS      1250
#define IDC_GOTO_CHANNEL_NUMBER         1251
#define IDD_EPG_SEARCH_STRING           1252
#define IDC_STRADIS_FORCE_PAL           1253
#define IDC_SOURCE_DEVICE_NUMBER_CAPTION 1255
#define IDC_SOURCE_DEVICE_NUMBER        1256
#define IDC_UI_SHOW_NON_VIDEO_PCR       1257
#define IDC_MDI_AVERAGE_BR              1258
#define IDC_SCHEDULER_USERNAME          1259
#define IDC_SCHEDULER_PASSWORD          1260
#define IDC_EPG_SEARCH_TITLE            1260
#define IDC_SCHEDULER_RECORD_DIRECTORY  1261
#define IDC_EPG_SEARCH_DESCRIPTION      1261
#define IDC_GRAPH_HISTORICAL_POINTS_CAPTION 1261
#define IDC_SCHEDULER_NO_DATE_TIME      1262
#define IDC_MONITOR_1_1                 1263
#define IDC_MONITOR_1_2                 1264
#define IDC_MONITOR_1_3                 1265
#define IDC_MONITOR_1_4                 1266
#define IDC_MONTHCALENDAR               1266
#define IDC_MONITOR_1_5                 1267
#define IDC_SAVE_CHART_DATA_ENABLED     1267
#define IDC_MONITOR_1_6                 1268
#define IDC_SAVE_CHART_DATA_FOLDER      1268
#define IDC_MONITOR_2_1                 1269
#define IDC_MONITOR_2_2                 1270
#define IDC_STRADIS_API_12              1270
#define IDC_MONITOR_2_3                 1271
#define IDC_STRADIS_API_16              1271
#define IDC_SPLIT_INFO_CAPTION          1271
#define IDC_MONITOR_2_4                 1272
#define IDC_BOMB_DONT_TELL              1272
#define IDC_MONITOR_2_5                 1273
#define IDC_MONITOR_2_6                 1274
#define IDC_EPG_DATETIMEPICKER_TIME     1274
#define IDC_MONITOR_3_1                 1275
#define IDC_EPG_DATETIMEPICKER_DATE     1275
#define IDC_MONITOR_3_2                 1276
#define IDC_EPG_MANUAL_SOURCE_PARAMETERS 1276
#define IDC_MONITOR_3_3                 1277
#define IDC_EPG_MANUAL_DURATION         1277
#define IDC_MONITOR_3_4                 1278
#define IDC_EPG_MANUAL_COMPLETE         1278
#define IDC_MONITOR_3_5                 1279
#define IDC_SCHEDULER_REQUIRES_LOGIN    1279
#define IDC_MONITOR_3_6                 1280
#define IDC_RECORD_ADVANCED_FILE        1280
#define IDC_MONITOR_3_7                 1281
#define IDC_RECORD_ADVANCED_MUX         1281
#define IDC_ADVANCED_RECORD_REMOVE_OLD  1281
#define IDC_MONITOR_3_8                 1282
#define IDC_ADVANCED_RECORD_REMOVE_OLD_SIZE 1282
#define IDC_MONITOR_3_9                 1283
#define IDC_ADVANCED_RECORD_UTC         1283
#define IDC_MONITOR_3_10                1284
#define IDC_ADVANCED_MUX_PID_DROP_ENABLE 1284
#define IDC_STREAM_MONITOR_ALARM_TIMEOUT 1285
#define IDC_MANUAL_PCR_PID_CAPTION      1286
#define IDC_MANUAL_CHANNEL_ES_TYPE_CAPTION 1287
#define IDC_MANUAL_CHANNEL_ES_PID_CAPTION 1288
#define IDC_EIT_LANGUAGE_FILTER_ENABLED 1290
#define IDC_EIT_LANGUAGE_FILTER_LANGUAGE 1291
#define IDC_EIT_LANGUAGE_FILTER_LANGUAGE_CAPTION 1292
#define IDC_SAVE_SETTINGS               1293
#define IDC_ARCHIVE_AUTO_DELETE_DELETE  1294
#define IDC_ARCHIVE_AUTO_DELETE_MOVE    1295
#define IDC_ARCHIVE_AUTO_DELETE_MOVE_LOCATION 1296
#define IDC_RECORD_TABLE_TABLE_NUMBER   1297
#define IDC_ARCHIVE_SELECT_ALARM_SOUND  1297
#define IDC_RECORD_TABLES_REMOVE        1298
#define IDC_RECORD_TABLES_OUTPUT_LOCATION 1299
#define IDC_RECORD_TABLES_OUTPUT_LOCATION_BROWSE 1300
#define IDC_RECORD_TABLES_RAW           1301
#define IDC_RECORD_TABLES_HEX_ASCII     1302
#define IDC_RECORD_TABLE_TABLE_CAPTION  1303
#define IDC_STREAM_MONITOR_ALARM_CLOCK_PCR 1304
#define IDC_STREAM_MONITOR_ALARM_CLOCK_SYSTEM 1305
#define IDC_ARCHIVE_SMTP_AUTHENTICATE   1305
#define IDC_STREAM_MONITOR_ALARM_EMAIL_ENABLED 1306
#define IDC_MONITOR_1_1_CAPTION         1307
#define IDC_MONITOR_1_2_CAPTION         1308
#define IDC_MONITOR_1_3_CAPTION         1309
#define IDC_MONITOR_1_4_CAPTION         1310
#define IDC_MONITOR_1_5_CAPTION         1311
#define IDC_MONITOR_1_6_CAPTION         1312
#define IDC_MONITOR_2_1_CAPTION         1313
#define IDC_MONITOR_2_2_CAPTION         1314
#define IDC_MONITOR_2_3_CAPTION         1315
#define IDC_MONITOR_2_4_CAPTION         1316
#define IDC_MONITOR_2_5_CAPTION         1317
#define IDC_MONITOR_2_6_CAPTION         1318
#define IDC_MONITOR_3_1_CAPTION         1319
#define IDC_MONITOR_3_2_CAPTION         1320
#define IDC_MONITOR_3_3_CAPTION         1321
#define IDC_MONITOR_3_4_CAPTION         1322
#define IDC_MONITOR_3_5_CAPTION         1323
#define IDC_MONITOR_3_6_CAPTION         1324
#define IDC_MONITOR_3_7_CAPTION         1325
#define IDC_MONITOR_3_8_CAPTION         1326
#define IDC_MONITOR_3_9_CAPTION         1327
#define IDC_MONITOR_3_10_CAPTION        1328
#define IDC_MAXIMUM_THUMBNAIL_THREADS_CAPTION 1329
#define IDC_MAXIMUM_H264_PICTURES_CAPTION 1330
#define IDC_MAXIMUM_H264_PICTURES       1331
#define IDC_EXPORT_INI_FOLDER           1332
#define IDC_EXPORT_NIT_DVBS2            1333
#define IDC_EXPORT_NIT_TURBO            1334
#define IDC_EXPORT_NIT_INCLUDE_IGNORED  1335
#define IDC_EPG_PREROLL                 1336
#define IDC_EPG_POSTROLL                1337
#define IDC_EPG_MANUAL_PROGRAM          1337
#define IDC_EPG_MANUAL_SOURCE_PARAMETERS_FORMAT 1338
#define IDC_EPG_MANUAL_COMPLETE_CAPTION 1339
#define IDC_DONT_ASK                    1340
#define IDC_ARCHIVE_RESTART             1341
#define IDC_EPG_MANUAL_CURRENT_MUX      1342
#define IDC_FORWARDER_INCLUDE_CA        1343
#define IDC_TABLE_VIEWER_SHOW_SECTIONS  1344
#define IDC_TABLE_VIEWER_SECTION_DISPLAY 1345
#define IDC_UPDATE_STEP_1               1346
#define IDC_UPDATE_STEP_2               1347
#define IDC_EPG_SCHEDULE_WAKE           1347
#define IDC_UPDATE_STEP_3               1348
#define IDC_EPG_DEFAULT_PREROLL         1348
#define IDC_UPDATE_STEP_4               1349
#define IDC_EPG_DEFAULT_POSTROLL        1349
#define IDC_FWD_188                     1349
#define IDC_UPDATE_STEP_5               1350
#define IDC_FWD_188_16                  1350
#define IDC_FWD_204                     1351
#define IDC_FWD_SYNC_INVERT             1352
#define IDC_FWD_SYNC_RANDOMIZER         1353
#define IDC_GPS_PORT                    1353
#define IDC_FWD_SYNC_INTERLEAVER        1354
#define IDC_GPS_DATA                    1354
#define IDC_GPS_RATE                    1355
#define IDC_GPS_OUTPUT_FILE             1356
#define IDC_GPS_LOG_TIMED               1357
#define IDC_GPS_LOG_SECONDS             1358
#define IDC_GPS_LOG_MANUAL              1359
#define IDC_GPS_LOG_INFO                1360
#define IDC_CC_MASK_1                   1363
#define IDC_CC_MASK_2                   1364
#define IDC_CC_DUMP_RAW_USER            1364
#define IDC_CC_MASK_3                   1365
#define IDC_CC_DUMP_EIA_608             1365
#define IDC_CC_MASK_4                   1366
#define IDC_CC_DUMP_EIA_708             1366
#define IDC_CC_MASK_5                   1367
#define IDC_CC_DUMP_WARNING             1367
#define IDC_CC_MASK_6                   1368
#define IDC_DONT_WARN                   1368
#define IDC_AUDIO_THUMBNAILS_ENABLED    1369
#define IDC_TITLE_PARSER_ENABLED        1370
#define IDC_AUDIO_TITLE_PMT_TYPE        1371
#define IDC_AUDIO_TITLE_MPEG_TABLE_NUMBER 1372
#define IDC_AUDIO_THUMBNAIL_BASE        1373
#define IDC_AUDIO_THUMBNAIL_BASE2       1374
#define IDC_GPS_GPS_TIME                1374
#define IDC_GPS_PC_LOCAL_TIME           1375
#define IDC_GPS_PC_UTC_TIME             1376
#define IDC_GPS_ERROR_LOG_ENABLED       1377
#define IDC_GPS_ERROR_LOG_MS            1378
#define ID_FILE_EXIT                    50001
#define ID_PLAYBACK_DIRECTSHOW          50003
#define ID_FILE_TUNE                    50005
#define ID_OPEN_NEW_FILE                50007
#define ID_FILE_RESTART_SOURCE          50007
#define ID_FILE_RESTARTASICARD          50008
#define ID_EXPORT_SAVETHUMBNAILS        50009
#define ID_SETTINGS_UNDERCONSTRUCTION   50010
#define ID_SETTINGS_DATAINPUTTHEADPRIORITY_HIGH 50011
#define ID_SETTINGS_DATAINPUTTHEADPRIORITY_NORMAL 50012
#define ID_SETTINGS_DATAINPUTTHEADPRIORITY_LOW 50013
#define ID_SETTINGS_STREAMPROCESSINGTHREADPRIORITY_HIGH 50014
#define ID_SETTINGS_STREAMPROCESSINGTHREADPRIORITY_NORMAL 50015
#define ID_SETTINGS_STREAMPROCESSINGTHREADPRIORITY_LOW 50016
#define ID_HELP_PURCHASETSREADER        50017
#define ID_SETTINGS_THUMBNAILTHREADPRIORITY_HIGH 50019
#define ID_SETTINGS_THUMBNAILTHREADPRIORITY_NORMAL 50020
#define ID_SETTINGS_THUMBNAILTHREADPRIORITY_LOW 50021
#define ID_PLAYBACK_XNSSERVER           50022
#define ID_SETTINGS_THUMBNAILTHREADPRIORITY_DISABLED 50023
#define ID_SETTINGS_XNSSERVERSETTINGS   50025
#define ID_HELP_SHOWMEMORYUSAGE         50026
#define ID_SETTINGS_KEEPPASTEITDATA     50027
#define ID_SETTINGS_TRACKMEMORYUSAGE    50028
#define ID_RECORD_RECORDPROGRAMTODVHS   50029
#define ID_SETTINGS_CONTROLDVHSDECK     50030
#define ID_SETTINGS_DVHSCONTROL_AUTOPOWERONOFF 50031
#define ID_HELP_RESETCONTINUITYCOUNTERS 50032
#define ID_SETTINGS_THUMBNAILTHREADPRIORITY_REFRESHRATE 50033
#define ID_FILE_SELECTSOURCE            50034
#define ID_SETTINGS_IGNOREEIT           50035
#define ID_FILE_DEFINEMANUALCHANNELS    50036
#define ID_FILE_LOADMANUALCHANNELS      50037
#define ID_FILE_SAVEMANUALCHANNELS      50038
#define ID_SETTINGS_THUMBNAILTHREADPRIORITY_ANIMATED 50039
#define ID_PLAYBACK_X                   50040
#define ID_PLUGINS_SOMETHING            50041
#define ID_SETTINGS_AUTOEXPANDPMTS      50042
#define ID_SETTINGS_IGNORETABLECRCERRORS 50043
#define ID_SETTINGS_FORCESTRADISINTOPAL 50044
#define ID_SETTINGS_XNSSERVER           50045
#define ID_FILE_STOPSOURCE              50046
#define ID_SETTINGS_VLC                 50048
#define ID_EXPORT_SAVEALLTHUMBNAILS     50049
#define ID_PLAYBACK_VLC_1               50050
#define ID_PLAYBACK_VLC_2               50051
#define ID_PLAYBACK_VLC_3               50052
#define ID_PLAYBACK_VLC_4               50053
#define ID_PLAYBACK_VLC_5               50054
#define ID_PLAYBACK_VLC_6               50055
#define ID_PLAYBACK_VLC_7               50056
#define ID_PLAYBACK_VLC_8               50057
#define ID_PLAYBACK_VLC_9               50058
#define ID_PLAYBACK_VLC_10              50059
#define ID_PLAYBACK_VLC_11              50060
#define ID_PLAYBACK_VLC_12              50061
#define ID_PLAYBACK_VLC_13              50062
#define ID_PLAYBACK_VLC_14              50063
#define ID_PLAYBACK_VLC_15              50064
#define ID_PLAYBACK_VLC_16              50065
#define ID_SETTINGS_BUFFERSIZES         50066
#define ID_SETTINGS_THUMBNAILTHREAD_SAVEALLUSESSAMENAME 50069
#define ID_SETTINGS_THUMBNAILTHREAD_FULLSIZESAVEDTHUMBNAILS 50070
#define ID_PLAYBACK_UDPSTREAMING_STREAMMUX 50072
#define ID_PLAYBACK_UDPSTREAMING_STREAMPROGRAM 50073
#define ID_SETTINGS_IGNOREPMTSABOVECH65500 50074
#define ID_SETTINGS_DVHS_FORCEPIDSTOBEATSCCOMPATIBLE 50075
#define ID_SETTINGS_COUNTCONTINUITYERRORS 50076
#define ID_EXPORT_XMLTVEXPORT           50077
#define ID_SETTINGS_RELOADMANUALCHANNELSAFTERRESTART 50078
#define ID_SETTINGS_HIDEWHENMINIMIZED   50079
#define ID_SETTINGS_SPLITRECORDFILENAMES 50080
#define ID_SETTINGS_THUMBNAILTHREAD_WAITFORCABEFOREPICTURE 50083
#define ID_SETTINGS_SERIALRECEVIERCONTROL 50084
#define ID_SETTINGS_IGNOREDCIIPMTCH80   50085
#define ID_SETTINGS_THUMBNAILTHREAD_SHOWSCRAMBLEDCHANNELS 50086
#define ID_SETTINGS_CONTROLSERVERSETTINGS 50087
#define ID_HELP_RESETCRCCOUNTERS        50088
#define ID_HELP_RESETSECTIONCOUNTERS    50089
#define ID_SETTINGS_KEEPSPECIALXMLCHARACTERS 50090
#define ID_HELP_SHOWPIDLIST             50091
#define ID_SETTINGS_SDTONLYFORCURRENTMUX 50092
#define ID_SETTINGS_DECIMALPIDS         50093
#define ID_FILE_DISEQCPOSITIONER        50094
#define ID_SETTINGS_DISABLEATSCRCPASSTHROUGH 50095
#define ID_SETTINGS_THUMBNAILTHREAD_HIDETHUMBNAILICONS 50096
#define ID_IDRIPPOPUP_SAVEPAYLOAD       50097
#define ID_IDRIPPOPUP_STOPSAVING        50098
#define ID_SETTINGS_IPDVBSETTINGS       50099
#define ID_IDRIPPOPUP_RETRANSMITPAYLOAD 50100
#define ID_IDRIPPOPUP_STOPTRANSMITTING  50101
#define ID_IDRNITPOPUP_RETUNETOTHISMUX  50102
#define ID_SETTINGS_DATAINPUTTHEADPRIORITY_CRITICAL 50103
#define ID_SETTINGS_AUTORESTARTONPATVERSIONCHANGE 50104
#define ID_IDRIPPOPUP_SAVEPAYLOAD_PID   50105
#define ID_IDRIPPOPUP_STOPSAVING_PID    50106
#define ID_IDRIPPOPUP_SAVEPAYLOAD_MAC   50107
#define ID_IDRIPPOPUP_STOPSAVING_MAC    50108
#define ID_IDRIPPOPUP_RETRANSMITPAYLOAD_MAC 50109
#define ID_IDRIPPOPUP_STOPTRANSMITTING_MAC 50110
#define ID_IDRIPPOPUP_RETRANSMITPAYLOAD_PID 50111
#define ID_IDRIPPOPUP_STOPTRANSMITTING_PID 50112
#define ID_SETTINGS_AUTOEXPANDIPS       50113
#define ID_SETTINGS_THUMBNAILTHREAD_LARGERTHUMBNAILS 50114
#define ID_PLAYBACK_ROKUHD1000          50115
#define ID_SETTINGS_ROKUHD1000          50116
#define ID_SETTINGS_PLAINCADESCRIPTORDECODING 50117
#define ID_VIEW_PIDPIECHART             50118
#define ID_IDRIPPOPUP_SAVEPAYLOADANDXXXIPHEADER 50119
#define ID_IDRIPPOPUP_SAVEPAYLOADXXXIPHEADERANDMPEHEADER 50120
#define ID_IDRIPPOPUPMAC_SAVEALLPAYLOADANDXXXIPHEADERSFORMAC 50121
#define ID_IDRIPPOPUPPID_SAVEALLPAYLOADANDXXXIPHEADERSONPID 50122
#define ID_IDRIPPOPUPMAC_SAVEALLPAYLOADXXXIPHEADERANDMPEHEADERSFORMAC 50123
#define ID_IDRIPPOPUPPID_SAVEALLPAYLOADXXXIPHEADERANDMPEHEADERSONPID 50124
#define ID_VIEW_PIDUSAGE2DPIECHART      50125
#define ID_VIEW_VIDEOBITRATECHART       50126
#define ID_VIEW_VIDEOBITRATEAREACHART   50127
#define ID_VIEW_MUXUSAGEAREACHART       50128
#define ID_VIEW_MUXUSAGELINECHART       50129
#define ID_FILE_IMPORTSATELLITELISTS_IMPORTSDX 50130
#define ID_FILE_IMPORTSATELLITELISTS_IMPORTCSV 50131
#define ID_VIEW_CHARTSETTINGS_STYLE_NOSTYLE 50134
#define ID_VIEW_CHARTSETTINGS_STYLE_LIGHTCOLORSWITHINSETBORDER 50135
#define ID_VIEW_CHARTSETTINGS_STYLE_LIGHTCOLORSWITHSHADOWBORDER 50136
#define ID_VIEW_CHARTSETTINGS_STYLE_LIGHTCOLORSWITHLINEBORDER 50137
#define ID_VIEW_CHARTSETTINGS_STYLE_LIGHTCOLORSWITHNOBORDER 50138
#define ID_VIEW_CHARTSETTINGS_STYLE_MEDIUMCOLORSWITHINSETBORDER 50139
#define ID_VIEW_CHARTSETTINGS_STYLE_MEDIUMCOLORSWITHSHADOWBORDER 50140
#define ID_VIEW_CHARTSETTINGS_STYLE_MEDIUMCOLORSWITHLINEBORDER 50141
#define ID_VIEW_CHARTSETTINGS_STYLE_MEDIUMCOLORSWITHNOBORDER 50142
#define ID_VIEW_CHARTSETTINGS_STYLE_DARKCOLORSWITHINSETBORDER 50143
#define ID_VIEW_CHARTSETTINGS_STYLE_DARKCOLORSWITHSHADOWBORDER 50144
#define ID_VIEW_CHARTSETTINGS_STYLE_DARKCOLORSWITHLINEBORDER 50145
#define ID_VIEW_CHARTSETTINGS_STYLE_DARKCOLORSWITHNOBORDER 50146
#define ID_VIEW_ACTIVEPIDSBYRATE        50147
#define ID_VIEW_ACTIVEPIDSBYPID         50148
#define ID_SETTINGS_TIMESTAMPPACKETS    50149
#define ID_HELP_RESETTEICOUNTERS        50150
#define ID_VIEW_SHOWEPGGRID             50151
#define ID_SETTINGS_EPGGRID             50152
#define ID_TEST_TEST                    50154
#define ID_SETTINGS_THUMBNAILTHREAD_DISPLAYFULLTHUMBNAILSONLY 50155
#define ID_VIEW_CHART_SETTINGS_XX       50156
#define ID_VIEW_CLOSEDCAPTIONS          50157
#define ID_VIEW_TABLELIST               50158
#define ID_VIEW_CHART_SETTINGS_REFRESHRATE 50159
#define ID_SETTINGS_AUTORESTART         50160
#define ID_SETTINGS_THUMBNAILTHREAD_ENABLEAUDIOTHUMBNAILS 50161
#define ID_RECORD_RECORDALLPROGRAMS     50162
#define ID_VIEW_ALWAYSONTOP             50163
#define ID_SETTINGS_REALTIMECHARTING    50164
#define ID_VIEW_ARCHIVEDFILES           50165
#define ID_SETTINGS_EITSERVER           50166
#define ID_HELP_RESETPIDCHART           50167
#define ID_HELP_RESETALL                50168
#define ID_SETTINGS_MAINPROCESSPRIORITY_REALTIME 50169
#define ID_SETTINGS_MAINPROCESSPRIORITY_HIGH 50170
#define ID_SETTINGS_MAINPROCESSPRIORITY_ABOVENORMAL 50171
#define ID_SETTINGS_MAINPROCESSPRIORITY_NORMAL 50172
#define ID_SETTINGS_MAINPROCESSPRIORITY_BELOWNORMAL 50173
#define ID_SETTINGS_MAINPROCESSPRIORITY_LOW 50174
#define ID_EXPORT_SAVEEPGDATA           50175
#define ID_VIEW_CHART_SETTINGS_PIDCHARTCOLORS 50176
#define ID_VIEW_CHART_PROGRAMUSAGESTACKEDBARCHART 50177
#define ID_VIEW_PMTTREE_EXPANDALLPMTS   50178
#define ID_VIEW_PMTTREE_CONTRACTALLPMTS 50179
#define ID_FILE_CICAMMENU               50180
#define ID_HELP_ABOUT                   50182
#define ID_VIEW_LARGEICONS              50183
#define ID_VIEW_SMALLICONS              50184
#define ID_VIEW_REFRESH                 50187
#define ID_FILE_DELETE                  50189
#define ID_FILE_EDIT                    50190
#define ID_FILE_NEW_PROFILE             50193
#define ID_VIEW_PROFILE_DETAILS         50194
#define ID_VIEW_PROFILE_LIST            50195
#define ID_VIEW_VIDEOMOSAIC             50197
#define ID_VIEW_CHART_VIDEOCOMPOSITIONCHART 50198
#define ID_IDRBATPOPUP_SELECTTHISBAT    50199
#define ID_FILE_LOADPIDLIST             50200
#define ID_IDRTDTPOPUP_SETPCTIMETOTHISTIME 50201
#define ID_FILE_CREATEDESKTOPSHORTCUT   50202
#define IDC_EDIT_COPY                   50203
#define IDC_EDIT_PASTE                  50204
#define ID_FILE_LAUNCHPROFILE           50205
#define ID_IDRPROFILESPOPUP_RENAME      50207
#define ID_SETTINGS_PLUGINSETTINGS      50209
#define ID_FORWARD_FORWARDTOUDP         50210
#define ID_IDRNITPOPUP_RETUNETOTHISMUX_SDT 50211
#define ID_VIEW_MDIINDEX                50212
#define ID_SETTINGS_SHOWNONVIDEOPCRICONS 50213
#define ID_VIEW_CHART_SIGNALCHART       50214
#define ID_VIEW_DESCRIPTORUSAGE         50215
#define ID_VIEW_STREAMMONITOR           50216
#define ID_VIEW_CHART_SETTINGS_SAVECHARTDATA 50218
#define ID_PLAYBACK_STRADISMPEG2DECODER_SETTINGS 50219
#define ID_IDRNITPOPUP_IGNORETHISNETWORK 50220
#define ID_VIEW_CHART_SETTINGS_STYLE_GRADIENTBITMAPBACKGROUND 50221
#define ID_SETTINGS_EMAILSETTINGS       50222
#define ID_IDRSTREAMMONITORPOPUP_MASKTHISITEM 50223
#define ID_IDRSTREAMMONITORPOPUP_RESETALARM 50224
#define ID_VIEW_CHART_PIDUSAGEVBRSTACKEDAREA 50225
#define ID_SETTINGS_WARNINGBEFOREOVERWRITNGRECORDINGS 50226
#define ID_SETTINGS_EITLANGUAGE         50227
#define ID_RECORD_RECORDTABLES          50228
#define ID_SETTINGS_THUMBNAILTHREAD_THUMBNAILSIZE_SMALL 50229
#define ID_SETTINGS_THUMBNAILTHREAD_THUMBNAILSIZE_NORMAL 50230
#define ID_SETTINGS_THUMBNAILTHREAD_THUMBNAILSIZE_LARGE 50231
#define ID_SETTINGS_THUMBNAILTHREAD_DISPLAYORDER_TOPDOWN 50232
#define ID_SETTINGS_THUMBNAILTHREAD_DISPLAYORDER_RIGHTTOLEFT 50233
#define ID_NIT_EXPORT_EXPORT_TO_INI     50234
#define ID_SETTINGS_THUMBNAILTHREAD_REFRESHNOW 50235
#define ID_IDREPGPOPUP_CANCELRECORDING  50236
#define ID_IDREPGPOPUP_RECORDOPTIONS    50238
#define ID_IDPCRPOPUP_USETHISPIDFORMUXRATE 50239
#define ID_IDRMANUALEPGCURRENT_FORDVBSTUNERS 50240
#define ID_IDRMANUALEPGCURRENT_FORADVANCEDSATELLITETUNERS 50241
#define ID_IDRMANUALEPGCURRENT_FORDVBTTUNERS 50242
#define ID_IDRMANUALEPGCURRENT_FORDVBCTUNERS 50243
#define ID_IDRMANUALEPGCURRENT_FORATSCTUNERS 50244
#define ID_HELP_CHECKFORNEWVERSION      50245
#define ID_IDRESPOPUP_REMOVEESBLACKLIST 50247
#define ID_EXPORT_GPSSIGNALEXPORT       50248
#define ID_FORWARD_SETTINGS             50249
#define ID_FORWARD_DLL_BASE             50250
#define ID_PLUGINS                      65530

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1186
#define _APS_NEXT_COMMAND_VALUE         50270
#define _APS_NEXT_CONTROL_VALUE         1379
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
