;
; Edit this file to cusomize MDTeleText.
;
; Place it in the current working directory of the DVB
; app or your Windows folder.
;

; Main window setttings.
;
[TeleText]

; Font, must be monospaced. Default is "Lucida Console", I recommend
; "Andale Mono" if you can find it (used to be included with IE 4 & 5).
;
Font=Lucida Console

; Select the preferred type of antialiasing. Default is 0.
; 0 = System default
; 1 = None
; 2 = Normal
; 3 = ClearType
;
Antialiasing=0

; Ignore the first column when centering the page in maximized and
; fullscreen modes. The first column on each page is usually empty
; anyway. Default is 1.
;
IgnoreFirstColumn=1

; Set the margin in % of screen width/height in fullscreen mode.
; Default is 10 %.
;
FullscreenMargin=10

; Window position on startup. Default is 0.
;
; 0 = Normal
; 1 = Minimized
; 2 = Maximized
; 3 = Fullscreen
;
WindowPosition=0


; Software subtitles settings.
;
[Subtitles]

; Font. Default is "MS Trebuchet", I recomend "Tiresias Screenfont" or
; "Tiresias PCfont" as it was designed for subtitling, unfortunately
; the font is not available for free.
;
Font=MS Trebuchet

; Select the preferred type of antialiasing. Default is 0.
;
Antialiasing=0

; Font size in % of display height. Default is 6.5 %.
;
Size=6.5

; Offset from the bottom edge in % of display height. Default is 6.5 %.
;
Bottom=6.5

; Offset from the left edge in % of the display width. Default is 5 %.
;
Left=5
