;TPS-AES stuff - System=V
[http://petsas.ifastnet.com/aes/petsas-1.php]
site_url=http://petsas.ifastnet.com/aes/petsas-1.php
regular_exp_pattern_to_find_key=(?s):\d{2}:(\w+?:\w+?)\s
key_part1_exp=
key_part2_exp=
key_index=01
Provider_id=007C00
System=V


[http://petsas.free.fr/aes/petsas-1.php]
site_url=http://petsas.free.fr/aes/petsas-1.php
regular_exp_pattern_to_find_key=(?s):\d{2}:(\w+?:\w+?)\s
key_part1_exp=
key_part2_exp=
key_index=01
Provider_id=007C00
System=V


[http://petsas.iitalia.com/aes/petsas-1.php]
site_url=http://petsas.iitalia.com/aes/petsas-1.php
regular_exp_pattern_to_find_key=(?s):\d{2}:(\w+?:\w+?)\s
key_part1_exp=
key_part2_exp=
key_index=01
Provider_id=007C00
System=V


[http://autoaes.prophp.org/Tofleboss.html]
site_url=http://autoaes.prophp.org/Tofleboss.html
regular_exp_pattern_to_find_key=(?s):\d{2}:(\w+?:\w+?)\s
key_part1_exp=
key_part2_exp=
key_index=01
Provider_id=007C00
System=V


[http://autoaes.cabspace.com/Tofleboss.html]
site_url=http://autoaes.cabspace.com/Tofleboss.html
regular_exp_pattern_to_find_key=(?s):\d{2}:(\w+?:\w+?)\s
key_part1_exp=
key_part2_exp=
key_index=01
Provider_id=007C00
System=V


[http://one.fsphost.com/autoaes/Tofleboss.html]
site_url=http://one.fsphost.com/autoaes/Tofleboss.html
regular_exp_pattern_to_find_key=(?s):\d{2}:(\w+?:\w+?)\s
key_part1_exp=
key_part2_exp=
key_index=01
Provider_id=007C00
System=V


[http://autoaes.atspace.name/Tofleboss.html]
site_url=http://autoaes.atspace.name/Tofleboss.html
regular_exp_pattern_to_find_key=(?s):\d{2}:(\w+?:\w+?)\s
key_part1_exp=
key_part2_exp=
key_index=01
Provider_id=007C00
System=V


[http://autoaes.50webs.com/Tofleboss.html]
site_url=http://autoaes.50webs.com/Tofleboss.html
regular_exp_pattern_to_find_key=(?s):\d{2}:(\w+?:\w+?)\s
key_part1_exp=
key_part2_exp=
key_index=01
Provider_id=007C00
System=V


[http://www.edu-consult.be/aes/]
site_url=http://www.edu-consult.be/aes/
regular_exp_pattern_to_find_key=(?s):\d{2}:(\w+?:\w+?)\s
key_part1_exp=
key_part2_exp=
key_index=01
Provider_id=007C00
System=V


[http://www.edu-consult.be/aes/linuxkeys.php]
site_url=http://www.edu-consult.be/aes/linuxkeys.php
regular_exp_pattern_to_find_key=(?s):\d{2}:(\w+?:\w+?)\s
key_part1_exp=
key_part2_exp=
key_index=01
Provider_id=007C00
System=V



;Nagra2 stuff - system=N

[cyberdbs-dish-01]
site_url=http://cyberdbs.com/forum/
regular_exp_pattern_to_find_key=(?s)>D!SH:\s</font><font\sface="verdana"\sSIZE=2\scolor="#0000FF">Key\s1\s-\s</font><font\sface="verdana"\sSIZE=2\scolor="#FF0000">(.+?)</fon
key_index=01
Provider_id=0101
System=N


[cyberdbs-dish-00]
site_url=http://cyberdbs.com/forum/
regular_exp_pattern_to_find_key=(?s)>D!SH:\s</font><font\sface="verdana"\sSIZE=2\scolor="#0000FF">Key\s0\s-\s</font><font\sface="verdana"\sSIZE=2\scolor="#FF0000">(.+?)</fon
key_index=00
Provider_id=0101
System=N


[cyberdbs-bell-01]
site_url=http://cyberdbs.com/forum/
regular_exp_pattern_to_find_key=(?s)>B3V:\s</font><font\sface="verdana"\sSIZE=2\scolor="#0000FF">Key\s1\s-\s</font><font\sface="verdana"\sSIZE=2\scolor="#FF0000">(.+?)</fon
key_index=01
Provider_id=0901
System=N

[cyberdbs-bell-00]
site_url=http://cyberdbs.com/forum/
regular_exp_pattern_to_find_key=(?s)\sB3V:\s</font><font\sface="verdana"\sSIZE=2\scolor="#0000FF">Key\s0\s-\s</font><font\sface="verdana"\sSIZE=2\scolor="#FF0000">(.+?)</fon
key_index=00
Provider_id=0901
System=N


