[Yankse]
Disabled=0
Log=0
LogBadKeys=0
LogCW=0
LogCurData=0
LogDecrypted=0
LogECM=0
LogFirstECM=0
LogPMT=0
ReadPMT=2
AutoECM=1	
FilterBogusECM=1
FilterUnknownECM=0
AllowAutoPIDS=1
CWDelay=750
UseSIDCache=1
UseECMThread=1
ShowOSD=0
ForcePMTCA=0
Language=0409-ENU
; remove the ; in front of DLLIDName for WTVP
;DLLIDName=Blue River	

; Normally not needed because the alternate TDA firmware is detected if used (line FIRM_DIR in multidec.ini)
; You may override the values here just in case if it's not detected or the magic values changed
;XorEven=0000000000000000
;XorOdd=0000000000000000
;SetDescrCommand=.... (4 hex value) only for MD9.x in case necessary

;LogCurData=1	; To log info about current channel in curdata.txt
;LogDecrypted=1 ; To log decrypted packets (Nagra & Conax) in yankse.log
;KeyPath=.	; absolute path (or relative to yankse.dll), to *.key files
[CardServer]
server=
port=-1
enabled=0
