/********************************************************
 * Some code. Copyright (C) 2003 by Pascal Massimino.   *
 * All Rights Reserved.      (http://skal.planet-d.net) *
 * For Educational/Academic use ONLY. See 'LICENSE.TXT'.*
 ********************************************************/
# Makefile
##################

####################################################################

clean:
	rm -f *~ *.o *.bak *.obj core toto*

#################################################################

