//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TSReader_SourceHelper.rc
//
#define IDC_POSITIONER                  3
#define IDD_TUNE_DVBT                   101
#define IDD_DIRECTV_LOGO                102
#define IDB_ATSC                        103
#define IDD_EDIT_ATSC_DESCRIPTION       104
#define IDD_INPUT_SETUP                 106
#define IDD_LNB_LO_WARNING              107
#define IDD_POSITIONER                  108
#define IDD_TUNE_UDP_MULTICAST          109
#define IDI_DELETE                      110
#define IDD_IMPORT_CSV                  111
#define IDI_ADD                         112
#define IDD_ADD_SATELLITE               113
#define IDD_ADD_ATSC                    114
#define IDI_USALS                       116
#define IDD_SCAN_ATSC_QAM_RANGE_START   117
#define IDD_SCAN_ATSC_QAM_RANGE         117
#define IDD_DVB_LOGO                    1000
#define IDC_SPECTRUM_INVERSE            1000
#define IDC_SPECTRUM_NORMAL             1001
#define IDC_BANDWIDTH_6MHz              1002
#define IDC_BANDWIDTH_7MHz              1003
#define IDC_BANDWIDTH_8MHz              1004
#define IDC_TERRESTRIAL_LIST            1005
#define IDC_NO_LNB_POWER                1006
#define IDC_ATSC_CHANNEL                1007
#define IDC_ATSC_SCAN                   1008
#define IDC_ATSC_SCAN_PROGRESS          1009
#define IDC_ATSC_SCAN_STATUS            1010
#define IDC_ATSC_SCAN_UHF               1011
#define IDC_ATSC_LIST                   1012
#define IDC_ATSC_EDIT                   1013
#define IDC_ATSC_CHANNEL_DESCRIPTION    1015
#define IDC_QAM_MODE                    1017
#define IDC_CABLE_LIST                  1018
#define IDC_MODULATION                  1019
#define IDC_CODE_RATE                   1020
#define IDC_INPUT_SETUP                 1021
#define IDC_INPUT_NONE                  1022
#define IDC_INPUT_TB_A                  1023
#define IDC_INPUT_TB_B                  1024
#define IDD_TUNE_TWINHAN                1025
#define IDD_TUNE_DVBS                   1025
#define IDC_LNB_TYPE                    1025
#define IDD_TUNE_DSS                    1026
#define IDC_LNB_A                       1026
#define IDD_TUNE_ATSC                   1027
#define IDC_LNB_B                       1027
#define IDD_TUNE_DVBC                   1028
#define IDC_LNB_SWITCH_FREQ             1028
#define IDD_TUNE_ADV                    1029
#define IDC_VOLT_POL                    1029
#define IDI_INFO                        1029
#define IDC_VOLT_BAND                   1030
#define IDD_TUNE_QAM                    1030
#define IDC_VOLT_OFF                    1031
#define IDD_EDIT_UDP_DESCRIPTION        1031
#define IDC_VOLT_14V                    1032
#define IDD_IMPORT_SDX                  1032
#define IDC_VOLT_18V                    1033
#define IDD_EDIT_DVBT_DESCRIPTION       1033
#define IDC_TONE_BAND                   1034
#define IDD_TUNE_UDP_UNICAST            1034
#define IDC_TONE_ON                     1035
#define IDD_EDIT_SATELLITE_DESCRIPTION  1035
#define IDC_TONE_OFF                    1036
#define IDD_EDIT_MUX_DESCRIPTION        1036
#define IDC_22KHZ                       1037
#define IDC_POSITIONER_NONE             1037
#define IDD_ADD_MUX                     1037
#define IDC_FREQUENCY                   1038
#define IDC_POSITIONER_DISEQC           1038
#define IDC_DONT_SHOW_AGAIN             1038
#define IDD_TUNE_TCP                    1038
#define IDC_HORZ                        1039
#define IDC_QAM_TYPE_IRC                1039
#define IDD_TUNE_ISDBT                  1039
#define IDC_VERT                        1040
#define IDC_QAM_TYPE_HRC                1040
#define IDC_SR                          1041
#define IDC_BUMP_EAST                   1041
#define IDC_LOF                         1042
#define IDC_BUMP_WEST                   1042
#define IDC_DISEQC4                     1043
#define IDC_MOVE_EAST                   1043
#define IDC_DISEQC1                     1044
#define IDC_MOVE_WEST                   1044
#define IDC_DISEQC2                     1045
#define IDC_SAT_POSITION                1045
#define IDC_DISEQC3                     1046
#define IDC_STORE_POSITION              1046
#define IDC_UDP_MULTICAST_ADDRESS       1046
#define IDC_GOTO_POSITION               1047
#define IDC_UDP_MULTICAST_PORT          1047
#define IDC_DISABLE_LIMITS              1048
#define IDC_DVBT_SCAN_STATUS            1048
#define IDC_SET_WEST_LIMIT              1049
#define IDC_SET_EAST_LIMIT              1050
#define IDC_DVBT_SCAN                   1050
#define IDC_DVBT_SCAN_PROGRESS          1051
#define IDC_POSITIONER_DISEQC1          1051
#define IDC_DVBT_EDIT                   1052
#define IDC_POSITIONER_DISEQC2          1052
#define IDC_DVBT_FREQUENCY              1053
#define IDC_POSITIONER_DISEQC3          1053
#define IDC_DVBT_CHANNEL_DESCRIPTION    1054
#define IDC_POSITIONER_DISEQC4          1054
#define IDC_ATSC_DELETE                 1055
#define IDC_POSITIONER_GOTO_USALS       1055
#define IDC_DVBT_DELETE                 1056
#define IDC_SATELLITE_DELETE            1056
#define IDC_TUNER_MUX_LIST              1057
#define IDC_DVBT_BANDPLAN               1057
#define IDC_TUNER_SATELLITE_LIST        1058
#define IDC_TUNER_MUX_TITLE             1059
#define IDC_SEPERATOR                   1060
#define IDC_INPUT_DISH                  1061
#define IDC_DISH_COMBO                  1062
#define IDC_DVB_FILENAME                1063
#define IDC_MUX_DELETE                  1063
#define IDC_DCII_FILENAME               1064
#define IDC_SATELLITE_USALS             1064
#define IDC_BROWSE_DVB                  1065
#define IDC_BROWSE_DCII                 1066
#define IDC_SDX_FOLDER                  1066
#define IDC_BROWSE_SDX                  1067
#define IDC_STATUS                      1068
#define IDC_UDP_RECENTLY_USED           1069
#define IDC_UDP_EDIT                    1070
#define IDC_UDP_DELETE                  1071
#define IDC_UDP_ADDRESS                 1072
#define IDC_UDP_STREAM_DESCRIPTION      1073
#define IDC_UDP_DESCRIPTION             1074
#define IDC_UDP_ADDRESS_CAPTION         1075
#define IDC_INTERFACE_ADDRESS           1076
#define IDC_AUTO_SELECT                 1078
#define IDC_AUTO_SELECT_START           1079
#define IDC_AUTO_SELECT_END             1080
#define IDC_LNB_A_CAPTION               1081
#define IDC_LNB_B_CAPTION               1082
#define IDC_AUTO_SELECT_FREQUENCY       1083
#define IDC_AUTO_SELECT_ORBITAL         1084
#define IDC_AUTO_SELECT_ORBITAL_DEG     1085
#define IDC_AUTO_SELECT_ORBITAL_EAST    1086
#define IDC_AUTO_SELECT_ORBITAL_WEST    1087
#define IDC_AUTO_SELECT_NETWORK         1088
#define IDC_AUTO_SELECT_NETWORK_ID      1089
#define IDC_SATELLITE_EDIT              1089
#define IDC_SATELLITE_ADD               1090
#define IDC_MUX_EDIT                    1091
#define IDC_SATELLITE_NAME              1091
#define IDC_MUX_ADD                     1092
#define IDC_SATELLITE_ORBITAL           1092
#define IDC_SATELLITE_ORBITAL_EAST      1093
#define IDC_SATELLITE_ORBITAL_WEST      1094
#define IDC_ORBITAL_POSITION            1095
#define IDC_SIGNAL_PARAMETERS           1096
#define IDC_MUX_NAME                    1097
#define IDC_ATSC_ADD                    1098
#define IDC_INPUT_SETUP_COMBO           1099
#define IDC_INPUT_POLARITY_VARIABLE     1100
#define IDC_INPUT_POLARITY_FIXEDH       1101
#define IDC_ACTIVE_ANTENNA_POWER        1101
#define IDC_INPUT_POLARITY_FIXEDV       1102
#define IDC_POSITIONER_LAT              1102
#define IDC_POSITIONER_LON              1103
#define IDC_ADD_MUX_LINEAR              1103
#define IDC_POSITIONER_ORBITAL_LOCATION 1104
#define IDC_ADD_MUX_CIRCULAR            1104
#define IDC_CHECK1                      1104
#define IDC_ISDBT_SCAN_PROGRESS         1105
#define IDC_ISDBT_SCAN_STATUS           1106
#define IDC_ISDBT_SCAN                  1107
#define IDC_ISDBT_EDIT                  1108
#define IDC_ISDBT_ADD                   1109
#define IDC_ISDBT_DELETE                1110
#define IDC_ISDBT_CHANNEL               1111
#define IDC_ISDBT_LIST                  1112
#define IDC_POSITIONER_NORTH            1113
#define IDC_POSITIONER_SOUTH            1114
#define IDC_POSITIONER_EAST             1115
#define IDD_SCAN_ATSC_QAM_RANGE_END     1115
#define IDC_POSITIONER_WEST             1116
#define IDC_POSITIONER_SAT_EAST         1117
#define IDC_POSITIONER_SAT_WEST         1118
#define IDC_POSITIONER_DEBUG            1119

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        118
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1120
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
