#ifndef IOCTL_H_
#define IOCTL_H_

#include <winioctl.h>

#define DST_VIDEO 0xAABB
#define DST_AUDIO 0xDDFF

// interface GUID for device
// {E18D1721-70B5-4de7-83B3-35436E3954ED}
DEFINE_GUID(GUID_DST_AUDIODEV, 
0xe18d1721, 0x70b5, 0x4de7, 0x83, 0xb3, 0x35, 0x43, 0x6e, 0x39, 0x54, 0xed);

// {7377DB61-E3CD-11d2-8A3F-0000F8784422}
DEFINE_GUID(GUID_DST_VIDEODEV, 
0x7377db61, 0xe3cd, 0x11d2, 0x8a, 0x3f, 0x0, 0x0, 0xf8, 0x78, 0x44, 0x22);

// Setup program, Change Channel
#define DST_IOCTL_SET_PROG \
	CTL_CODE( DST_VIDEO, 0xA00, METHOD_BUFFERED, FILE_ANY_ACCESS )

// Sart TS capture
#define DST_IOCTL_START_CAP \
	CTL_CODE( DST_AUDIO, 0xB00, METHOD_BUFFERED, FILE_ANY_ACCESS )

// Stop TS capture
#define DST_IOCTL_STOP_CAP \
	CTL_CODE( DST_AUDIO, 0xB10, METHOD_BUFFERED, FILE_ANY_ACCESS )

// Get RISC_PC 
#define DST_IOCTL_GET_DATABUFF_BLOCK \
	CTL_CODE( DST_AUDIO, 0xB20, METHOD_BUFFERED, FILE_ANY_ACCESS )

//update on 21 July
// Query Tuner QOS & Program info
#define DST_IOCTL_SET_INFO \
	CTL_CODE( DST_VIDEO, 0xA20, METHOD_BUFFERED, FILE_ANY_ACCESS )

// Query Info
#define DST_GET_EEPROM_INFO \
	CTL_CODE( DST_VIDEO, 0xA22, METHOD_BUFFERED, FILE_ANY_ACCESS )

// Scan the First step
#define DST_IOCTL_SCAN_START \
	CTL_CODE( DST_VIDEO, 0xA40, METHOD_BUFFERED, FILE_ANY_ACCESS )

// Scan the second step
#define DST_IOCTL_SCAN_WAITING \
	CTL_CODE( DST_VIDEO, 0xA60, METHOD_BUFFERED, FILE_ANY_ACCESS )

// Scan thirth step
#define DST_IOCTL_SCAN_END \
	CTL_CODE( DST_VIDEO, 0xA80, METHOD_BUFFERED, FILE_ANY_ACCESS )

//CI 
#define DST_IOCTL_CA_WRITE \
	CTL_CODE( DST_VIDEO, 0xA81, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define DST_IOCTL_CA_READ \
	CTL_CODE( DST_VIDEO, 0xA82, METHOD_BUFFERED, FILE_ANY_ACCESS )

// Reset RDC8820
#define DST_IOCTL_RDC8820_RESET \
	CTL_CODE( DST_VIDEO, 0xA84, METHOD_BUFFERED, FILE_ANY_ACCESS )

// Query Info
#define DST_GET_DEVICE_INFO \
	CTL_CODE( DST_VIDEO, 0xA21, METHOD_BUFFERED, FILE_ANY_ACCESS )

//DTT Card Iocontrol define
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
//AUDIO model
#define DTT_START_CAP\
	  CTL_CODE( DST_AUDIO, 0xB01, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define DTT_STOP_CAP \
	  CTL_CODE( DST_AUDIO, 0xB11, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define DTT_GET_RISCPC \
	  CTL_CODE( DST_AUDIO, 0xB21, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define DTT_GET_ADDR \
	  CTL_CODE( DST_AUDIO, 0xB31, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define DTT_GET_INTERNAL_ADDR \
	  CTL_CODE( DST_AUDIO, 0xB33, METHOD_BUFFERED, FILE_ANY_ACCESS )

//VIDEO model
#define DTT_SET_CHANNEL \
	 CTL_CODE( DST_VIDEO, 0xA01, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define DTT_SET_INFO \
	 CTL_CODE( DST_VIDEO, 0xA21, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define DTT_SCAN_START \
	 CTL_CODE( DST_VIDEO, 0xA41, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define DTT_SCAN_WAITING \
	 CTL_CODE( DST_VIDEO, 0xA61, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define DTT_SCAN_WAITINGEVENT \
	 CTL_CODE( DST_VIDEO, 0xA71, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define DTT_SCAN_END \
     CTL_CODE( DST_VIDEO, 0xA88, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define DTT_GET_MAC \
	 CTL_CODE( DST_VIDEO, 0xA87, METHOD_BUFFERED, FILE_ANY_ACCESS )

// Set channel, Change Channel
#define ANALOG_SET_CHANNEL \
	CTL_CODE( DST_VIDEO, 0xC00, METHOD_BUFFERED, FILE_ANY_ACCESS )

//read the tda9886 register
#define ANALOG_READ_REG\
	CTL_CODE( DST_VIDEO, 0xC01, METHOD_BUFFERED, FILE_ANY_ACCESS )

//get lock status
#define ANALOG_GET_STATUS\
	CTL_CODE( DST_VIDEO, 0xC02, METHOD_BUFFERED, FILE_ANY_ACCESS )

//special command
#define ANALOG_SET_INFO \
	CTL_CODE( DST_VIDEO, 0xC03, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define ANALOG_SET_STANDARD \
	CTL_CODE( DST_VIDEO, 0xC07, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define ANALOG_GET_STANDARD \
	CTL_CODE( DST_VIDEO, 0xC08, METHOD_BUFFERED, FILE_ANY_ACCESS )

//set the color format register value
#define ANALOG_SET_COLOR\
	CTL_CODE( DST_VIDEO, 0xc36, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define ANALOG_GET_COLOR\
	CTL_CODE( DST_VIDEO, 0xc37, METHOD_BUFFERED, FILE_ANY_ACCESS )

//start capture
#define ANALOG_START_CAP \
	CTL_CODE( DST_VIDEO, 0xC10, METHOD_BUFFERED, FILE_ANY_ACCESS )

//stop capture
#define ANALOG_STOP_CAP \
	CTL_CODE( DST_VIDEO, 0xC20, METHOD_BUFFERED, FILE_ANY_ACCESS )

//read bt878 register
#define ANALOG_TEST_READ \
	CTL_CODE( DST_VIDEO, 0xC21, METHOD_BUFFERED, FILE_ANY_ACCESS )

//reset bt878 register
#define ANALOG_RESET_BT878 \
	CTL_CODE( DST_VIDEO, 0xC22, METHOD_BUFFERED, FILE_ANY_ACCESS )

//write bt878 register
#define ANALOG_WRITE_BT878 \
	CTL_CODE( DST_VIDEO, 0xC23, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define ANALOG_GET_OFFSET\
	CTL_CODE( DST_VIDEO, 0xc30, METHOD_BUFFERED, FILE_ANY_ACCESS )

//get the pci configration register value
#define ANALOG_GET_PCI\
	CTL_CODE( DST_VIDEO, 0xc40, METHOD_BUFFERED, FILE_ANY_ACCESS )

//set the BRIGHTNESS register value
#define ANALOG_SET_BRIGHTNESS\
	CTL_CODE( DST_VIDEO, 0xc31, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define ANALOG_GET_BRIGHTNESS\
	CTL_CODE( DST_VIDEO, 0xc41, METHOD_BUFFERED, FILE_ANY_ACCESS )

//set the CONTRAST register value
#define ANALOG_SET_CONTRAST\
	CTL_CODE( DST_VIDEO, 0xc32, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define ANALOG_GET_CONTRAST\
	CTL_CODE( DST_VIDEO, 0xc42, METHOD_BUFFERED, FILE_ANY_ACCESS )

//set the SATURATION register value
#define ANALOG_SET_SATURATION\
	CTL_CODE( DST_VIDEO, 0xc33, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define ANALOG_GET_SATURATION\
	CTL_CODE( DST_VIDEO, 0xc43, METHOD_BUFFERED, FILE_ANY_ACCESS )

//set the HUE register value
#define ANALOG_SET_HUE\
	CTL_CODE( DST_VIDEO, 0xc34, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define ANALOG_GET_HUE\
	CTL_CODE( DST_VIDEO, 0xc44, METHOD_BUFFERED, FILE_ANY_ACCESS )

//determine whether capture vbi data
#define ANALOG_SET_VBI\
	CTL_CODE( DST_VIDEO, 0xc24, METHOD_BUFFERED, FILE_ANY_ACCESS )

//get the vbi packet size
#define ANALOG_GET_VBI\
	CTL_CODE( DST_VIDEO, 0xc25, METHOD_BUFFERED, FILE_ANY_ACCESS )

//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

#endif



