
##########################################################################
#
# OPTIONS DEFINITION
#
# filepath	: where you want to save the softcam.key
# viewResult	: 1 -> let you see the keys
#		  0 -> close the window
# getDish	: print the dish keys to the softcam
# getBev	: print the bev keys to the softcam
# getBev0905	: print the 0905 provider keys
# getBev0906	: print the 0906 provider keys
#
# website	: the website from where you want to get the keys
# spaced	: 1 -> keys are given with spaces    ( 01 01 01 ... )
#		  0 -> keys are given without spaces ( 01010101 ... ) 
# dishKeyTag0	: a string just before the dish key 00 on the same line
# dishKeyTag1	: a string just before the dish key 01 on the same line
# bevKeyTag0	: a string just before the bev  key 00 on the same line
# bevKeyTag1	: a string just before the bev  key 01 on the same line
# bev0905Tag0	: a string just before the bev 0905 00 on the same line
# bev0905Tag1	: a string just before the bev 0905 01 on the same line
# bev0906Tag0	: a string just before the bev 0906 00 on the same line
# bev0906Tag1	: a string just before the bev 0906 01 on the same line
#
# line starting with '#' are commented
# option value MUST be surrounded by quotes (ex.: "value")
# 
# any website which contain keys can be used:
#	-enter the complete adress without "http://"
#	-indicated if there is spaces
#       -enter the tag before each keys
#
##########################################################################


filepath=".\"
viewResult="1"
getDish="1"
getBev="1"
getBev0905="1"
getBev0906="1"



#
# WEBSITE SECTION
#
# If two identical options are uncommented, getKeys will take the first 
#


website="www.tvkeyz.com"
spaced="1"
dishKeyTag0="86:"
dishKeyTag1="96:"
bevKeyTag0="86:"
bevKeyTag1="96:"
bev0905Tag0="06:"
bev0905Tag1="46:"
bev0906Tag0="06:"
bev0906Tag1="46:"


#website="elitecoders.net/?page=Keys/"
#spaced="0"
#dishKeyTag0="86:"
#dishKeyTag1="96:"
#bevKeyTag0="86:"
#bevKeyTag1="96:"
#bev0905Tag0="06:"
#bev0905Tag1="46:"
#bev0906Tag0="06:"
#bev0906Tag1="46:"

#don't give 0905 & 0906
#website="www.maestra.tv/keys/"
#spaced="1"
#dishKeyTag0="Key (86) 00"
#dishKeyTag1="Key (96) 01"
#bevKeyTag0="Key (86) 00"
#bevKeyTag1="Key (96) 01"

#don't give 0905 & 0906
#website="romprotect.com/PremiumCP/Keys.php"
#spaced="0"
#dishKeyTag0="KEY0"
#dishKeyTag1="KEY1"
#bevKeyTag0="AUX0"
#bevKeyTag1="AUX1"
